### ISSUE TITLE
ODP Upgrade (19.3+)

### ISSUE THREAD

**Issue by carmanj** [avrahamcool/Aleph1.Oracle.DataAccess.AllFrameworks#1]
Hi there,

Is there any intention of updating this against the 19.3.+ release, or even anything that might be newer out? I know the Oracle.ManagedDataAccess is at 19.11 currently.

Thanks!

**Comment by avrahamcool** [comment]
yeah.. should not be a problem.
just need to find all the appropriate downloads from Oracle. (32/64 bit, .net2/.net4)
Oracle don't make life easy with this unmanaged DLL.

from this link - https://www.oracle.com/database/technologies/dotnet-odacdeploy-downloads.html

this is the latest version I see: (in the XCOPY section)
64-bit Unmanaged ODP.NET 19.10 (84,134,103 bytes)
32-bit Unmanaged ODP.NET 19.10 (79,256,193 bytes)

where did you find 19.11?

also: they don't change the version of the DLL, so this will be weird in the nuget version.
the version in the DLL I just downloaded (19.10) is still 122.19.1

well - I see they update the product version based on the publish date.
122.19.1:20201225 for the 32 bit
122.19.1:20201224 for the 64bit

so I guess I would call them the same.

**Comment by carmanj** [comment]
Ah, I hadn't realized that. I happened to notice it in nuget, but only for the Oracle.ManagedDataAccess (https://www.nuget.org/packages/Oracle.ManagedDataAccess/). I figured they'd keep the managed and unmanaged versions in sync, but apparently not.

Thanks!

**Comment by avrahamcool** [comment]
I've uploaded the latest DLL's as nuget packages.
they should be available soon. (after validation etc'..)
